version: "2"
services:
  user_api:
    build:
      context: .
    restart: always
    volumes:
    - .:/go/src/github.com/emurmotol/project/user_api
    image: emurmotol/user_api:latest
    container_name: user_api
    ports:
    - 8083:8083
    - 8084:8084
    environment:
    - JWT_PUBLIC_KEY=/go/src/github.com/emurmotol/project/user_api/certs/jwt.key.pub