// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_api.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetByUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUsernameRequest) Reset()         { *m = GetByUsernameRequest{} }
func (m *GetByUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*GetByUsernameRequest) ProtoMessage()    {}
func (*GetByUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37757815a5c2e68a, []int{0}
}

func (m *GetByUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUsernameRequest.Unmarshal(m, b)
}
func (m *GetByUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUsernameRequest.Marshal(b, m, deterministic)
}
func (m *GetByUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUsernameRequest.Merge(m, src)
}
func (m *GetByUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_GetByUsernameRequest.Size(m)
}
func (m *GetByUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUsernameRequest proto.InternalMessageInfo

func (m *GetByUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetByUsernameReply struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUsernameReply) Reset()         { *m = GetByUsernameReply{} }
func (m *GetByUsernameReply) String() string { return proto.CompactTextString(m) }
func (*GetByUsernameReply) ProtoMessage()    {}
func (*GetByUsernameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_37757815a5c2e68a, []int{1}
}

func (m *GetByUsernameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUsernameReply.Unmarshal(m, b)
}
func (m *GetByUsernameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUsernameReply.Marshal(b, m, deterministic)
}
func (m *GetByUsernameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUsernameReply.Merge(m, src)
}
func (m *GetByUsernameReply) XXX_Size() int {
	return xxx_messageInfo_GetByUsernameReply.Size(m)
}
func (m *GetByUsernameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUsernameReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUsernameReply proto.InternalMessageInfo

func (m *GetByUsernameReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetByUsernameReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37757815a5c2e68a, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type User struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=Role,proto3" json:"Role,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt            string   `protobuf:"bytes,8,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_37757815a5c2e68a, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *User) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type CreateUserReply struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_37757815a5c2e68a, []int{4}
}

func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (m *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(m, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

func (m *CreateUserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GetByUsernameRequest)(nil), "pb.GetByUsernameRequest")
	proto.RegisterType((*GetByUsernameReply)(nil), "pb.GetByUsernameReply")
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*CreateUserReply)(nil), "pb.CreateUserReply")
}

func init() { proto.RegisterFile("user_api.proto", fileDescriptor_37757815a5c2e68a) }

var fileDescriptor_37757815a5c2e68a = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4e, 0xbb, 0x40,
	0x10, 0xc6, 0x03, 0xa5, 0x2d, 0x9d, 0x7f, 0xfe, 0x35, 0x8e, 0xd5, 0x6c, 0x48, 0x0f, 0x86, 0x93,
	0x27, 0x0e, 0x78, 0xf1, 0x8a, 0xd2, 0x68, 0x6f, 0x86, 0xa4, 0x67, 0x03, 0x61, 0x0e, 0x24, 0x54,
	0xd6, 0x65, 0x89, 0xe1, 0x05, 0x7c, 0x40, 0x9f, 0xc8, 0xec, 0x6e, 0x0b, 0xb6, 0x96, 0x98, 0x78,
	0xeb, 0xf7, 0xfd, 0x66, 0xe6, 0x9b, 0x32, 0x0b, 0xf3, 0xa6, 0x26, 0xf1, 0x92, 0xf2, 0x22, 0xe0,
	0xa2, 0x92, 0x15, 0xda, 0x3c, 0xf3, 0x43, 0x58, 0x3c, 0x92, 0xbc, 0x6f, 0x37, 0x35, 0x89, 0xd7,
	0x74, 0x4b, 0x09, 0xbd, 0x35, 0x54, 0x4b, 0xf4, 0xc0, 0xdd, 0x5b, 0xcc, 0xba, 0xb6, 0x6e, 0x66,
	0x49, 0xa7, 0xfd, 0x27, 0xc0, 0xa3, 0x1e, 0x5e, 0xb6, 0xb8, 0x04, 0x47, 0x19, 0xba, 0xfa, 0x5f,
	0xe8, 0x06, 0x3c, 0x0b, 0x94, 0x4e, 0xb4, 0x8b, 0x0b, 0x18, 0xaf, 0x84, 0xa8, 0x04, 0xb3, 0xf5,
	0x30, 0x23, 0xfc, 0x06, 0xce, 0x1f, 0x04, 0xa5, 0x92, 0x74, 0xe5, 0xef, 0xd1, 0x7a, 0xcc, 0x36,
	0x2d, 0xca, 0x6e, 0x8c, 0x12, 0xaa, 0xe3, 0x39, 0xad, 0xeb, 0xf7, 0x4a, 0xe4, 0x6c, 0x64, 0x3a,
	0xf6, 0x1a, 0x11, 0x9c, 0xa4, 0x2a, 0x89, 0x39, 0xda, 0xd7, 0xbf, 0xfd, 0x4f, 0xcb, 0xec, 0x8a,
	0x73, 0xb0, 0xd7, 0xf1, 0x2e, 0xc4, 0x5e, 0xc7, 0x07, 0xd1, 0xf6, 0x50, 0xf4, 0x68, 0x28, 0xda,
	0x19, 0x88, 0x1e, 0xf7, 0xd1, 0xb8, 0x84, 0x99, 0xf9, 0xc7, 0x79, 0x24, 0xd9, 0x44, 0x83, 0xde,
	0x50, 0x74, 0xc3, 0xf3, 0x1d, 0x9d, 0x1a, 0xda, 0x19, 0x8a, 0xc6, 0x54, 0x92, 0xa1, 0xae, 0xa1,
	0x9d, 0xe1, 0xaf, 0xe0, 0xec, 0xfb, 0xb7, 0xfc, 0xe3, 0x49, 0xc2, 0x0f, 0x0b, 0xa6, 0x0a, 0x47,
	0xbc, 0xc0, 0x08, 0xfe, 0x1f, 0x1c, 0x1a, 0x99, 0x1a, 0x71, 0xea, 0xbd, 0x78, 0x57, 0x27, 0x88,
	0x5a, 0xe1, 0x0e, 0xa0, 0xdf, 0x0a, 0x2f, 0x55, 0xd5, 0x8f, 0x8b, 0x7b, 0x17, 0xc7, 0x36, 0x2f,
	0xdb, 0x6c, 0xa2, 0x1f, 0xe9, 0xed, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xec, 0xee, 0xde,
	0xb6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserApiClient is the client API for UserApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserApiClient interface {
	GetByUsername(ctx context.Context, in *GetByUsernameRequest, opts ...grpc.CallOption) (*GetByUsernameReply, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
}

type userApiClient struct {
	cc *grpc.ClientConn
}

func NewUserApiClient(cc *grpc.ClientConn) UserApiClient {
	return &userApiClient{cc}
}

func (c *userApiClient) GetByUsername(ctx context.Context, in *GetByUsernameRequest, opts ...grpc.CallOption) (*GetByUsernameReply, error) {
	out := new(GetByUsernameReply)
	err := c.cc.Invoke(ctx, "/pb.UserApi/GetByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userApiClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := c.cc.Invoke(ctx, "/pb.UserApi/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserApiServer is the server API for UserApi service.
type UserApiServer interface {
	GetByUsername(context.Context, *GetByUsernameRequest) (*GetByUsernameReply, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
}

func RegisterUserApiServer(s *grpc.Server, srv UserApiServer) {
	s.RegisterService(&_UserApi_serviceDesc, srv)
}

func _UserApi_GetByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserApiServer).GetByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserApi/GetByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserApiServer).GetByUsername(ctx, req.(*GetByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserApi_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserApiServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserApi/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserApiServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserApi",
	HandlerType: (*UserApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByUsername",
			Handler:    _UserApi_GetByUsername_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserApi_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_api.proto",
}
