// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/emurmotol/project/auth/pkg/endpoint"
	pb "github.com/emurmotol/project/auth/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	login       grpc.Handler
	restricted  grpc.Handler
	healthCheck grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.AuthServer {
	return &grpcServer{
		healthCheck: makeHealthCheckHandler(endpoints, options["HealthCheck"]),
		login:       makeLoginHandler(endpoints, options["Login"]),
		restricted:  makeRestrictedHandler(endpoints, options["Restricted"]),
	}
}
